# name: Build and unit test

# on:
#   pull_request:
#     branches: [main]
#     types: [opened, synchronize, reopened]
#   workflow_call:
#   workflow_dispatch:

# env:
#   ARTIFACT_UPLOAD_PATH: "./output"

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3

#       - name: Setup .NET SDK 6 LTS
#         uses: actions/setup-dotnet@v3
#         with:
#           dotnet-version: "6.x"

#       - name: Build
#         run: dotnet build -c Release

#       - name: Test
#         run: dotnet test --logger 'console;verbosity=detailed'

#       - name: Publish
#         if: github.event.pull_request.merged == true
#         run: dotnet publish -c Release -o ${{env.ARTIFACT_UPLOAD_PATH}}

#       - name: Upload artifact
#         if: github.event.pull_request.merged == true
#         uses: actions/upload-artifact@v3
#         with:
#           name: .net-app
#           path: ${{env.ARTIFACT_UPLOAD_PATH}}
