name: Deploy to App Service

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  ARTIFACT_NAME: "web-app"
  ARTIFACT_UPLOAD_PATH: "./output"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build-app-service.yml

      - name: Publish
        run: dotnet publish -c Release -o ${{env.ARTIFACT_UPLOAD_PATH}}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: ${{env.ARTIFACT_UPLOAD_PATH}}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: dev
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{env.ARTIFACT_NAME}}
      - name: Login in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy
        if: success()
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{vars.APP_SERVICE_NAME}}
          package: "."
